# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm/joint1:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: true
    max_acceleration: 5
  arm/joint2:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: true
    max_acceleration: 5
  arm/joint3:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: true
    max_acceleration: 5
  arm/joint4:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: true
    max_acceleration: 5
  gripper/joint1:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: true
    max_acceleration: 20
  gripper/joint1_mimic:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: true
    max_acceleration: 20
  gripper/joint2:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: true
    max_acceleration: 20
  gripper/joint2_mimic:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: true
    max_acceleration: 20
